### ISSUE TITLE
Error on 'Entering Password...'

### ISSUE THREAD

**Issue by chandrasg** [nmiodice/id4-reservation-tracker#1]
Thanks for sharing this! I get the following error:

```
Loading VW reservation page...
Entering username...
Submitting username...
Entering password...
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    main()
  File "main.py", line 63, in main
    passwordInput = WebDriverWait(driver, 10).until(
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55ff98888a23 <unknown>
#1 0x55ff98353e18 <unknown>
#2 0x55ff9838a151 <unknown>
#3 0x55ff9838a311 <unknown>
#4 0x55ff983bcec4 <unknown>
#5 0x55ff983a79bd <unknown>
#6 0x55ff983bac5b <unknown>
#7 0x55ff983a7883 <unknown>
#8 0x55ff9837d3fa <unknown>
#9 0x55ff9837e4c5 <unknown>
#10 0x55ff988b816d <unknown>
#11 0x55ff988ce5bb <unknown>
#12 0x55ff988b9e75 <unknown>
#13 0x55ff988cee85 <unknown>
#14 0x55ff988ad86f <unknown>
#15 0x55ff988e9ae8 <unknown>
#16 0x55ff988e9c68 <unknown>
#17 0x55ff98904aad <unknown>
#18 0x7f018293eea7 <unknown>

```

I tried exporting the username and password with and without quotes and get the same error. What am I getting wrong?

**Comment by nmiodice** [comment]
Hmm, I didn't see that while testing. It is tough to tell from the logs you have here, so I added a new change that will dump out the HTML on the page, along with the debug output you see here.

Can you pull that change (`git pull`) and then run it again? You should see a similar failure, but with a ton more debugging output that will help me understand a bit more about what's going on.

**Note**: the HTML in the debugging output *may contain your username/password*. Please make sure that it is omitted from the content you paste into this issue! **The code does attempt to replace the username and password with placeholder values, but please double check that you aren't uploading any sensitive information**

**Comment by nmiodice** [comment]
Also small world, @chandrasg... I did my masters @ UPenn for CS :). Congrats on your professorship there!

**Comment by chandrasg** [comment]
that's awesome! thank you! here is the HTML debugging output; password and email were successfully obfuscated :)

```
Loading VW reservation page...
Entering username...
Submitting username...
Entering password...
<html lang="en" xmlns="http://www.w3.org/1999/html"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="identitykit" content="loginIdentifier">
    
<script type="text/javascript" src="https://bam.nr-data.net/1/0452f39fd4?a=70920201&amp;v=1215.1253ab8&amp;to=NVVTZkpXXRcFURIKWgwfYkJKX10DJ10IF0cNXF1XShlIBwhbAw1BK1RMHVRZVA0KHQ8HUAxEWFRRU0FETHUjNxw%3D&amp;rst=211&amp;ck=1&amp;ref=https://identity.na.vwgroup.io/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/login/identifier&amp;ap=26&amp;be=131&amp;fe=196&amp;dc=169&amp;perf=%7B%22timing%22:%7B%22of%22:1643481905405,%22n%22:0,%22u%22:117,%22r%22:1,%22ue%22:117,%22re%22:45,%22f%22:46,%22dn%22:46,%22dne%22:46,%22c%22:46,%22ce%22:46,%22rq%22:47,%22rp%22:104,%22rpe%22:106,%22dl%22:118,%22di%22:168,%22ds%22:168,%22de%22:170,%22dc%22:195,%22l%22:195,%22le%22:196%7D,%22navigation%22:%7B%22rc%22:1%7D%7D&amp;fp=185&amp;fcp=185&amp;jsonp=NREUM.setToken"></script><script src="https://js-agent.newrelic.com/nr-1215.min.js"></script><script type="text/javascript">(window.NREUM||(NREUM={})).init={ajax:{deny_list:["bam.nr-data.net"]}};(window.NREUM||(NREUM={})).loader_config={licenseKey:"0452f39fd4",applicationID:"70920201"};window.NREUM||(NREUM={}),__nr_require=function(t,e,n){function r(n){if(!e[n]){var i=e[n]={exports:{}};t[n][0].call(i.exports,function(e){var i=t[n][1][e];return r(i||e)},i,i.exports)}return e[n].exports}if("function"==typeof __nr_require)return __nr_require;for(var i=0;i<n.length;i++)r(n[i]);return r}({1:[function(t,e,n){function r(){}function i(t,e,n,r){return function(){return s.recordSupportability("API/"+e+"/called"),o(t+e,[u.now()].concat(c(arguments)),n?null:this,r),n?void 0:this}}var o=t("handle"),a=t(10),c=t(11),f=t("ee").get("tracer"),u=t("loader"),s=t(4),d=NREUM;"undefined"==typeof window.newrelic&&(newrelic=d);var p=["setPageViewName","setCustomAttribute","setErrorHandler","finished","addToTrace","inlineHit","addRelease"],l="api-",v=l+"ixn-";a(p,function(t,e){d[e]=i(l,e,!0,"api")}),d.addPageAction=i(l,"addPageAction",!0),d.setCurrentRouteName=i(l,"routeName",!0),e.exports=newrelic,d.interaction=function(){return(new r).get()};var m=r.prototype={createTracer:function(t,e){var n={},r=this,i="function"==typeof e;return o(v+"tracer",[u.now(),t,n],r),function(){if(f.emit((i?"":"no-")+"fn-start",[u.now(),r,i],n),i)try{return e.apply(this,arguments)}catch(t){throw f.emit("fn-err",[arguments,this,t],n),t}finally{f.emit("fn-end",[u.now()],n)}}}};a("actionText,setName,setAttribute,save,ignore,onEnd,getContext,end,get".split(","),function(t,e){m[e]=i(v,e)}),newrelic.noticeError=function(t,e){"string"==typeof t&&(t=new Error(t)),s.recordSupportability("API/noticeError/called"),o("err",[t,u.now(),!1,e])}},{}],2:[function(t,e,n){function r(t){if(NREUM.init){for(var e=NREUM.init,n=t.split("."),r=0;r<n.length-1;r++)if(e=e[n[r]],"object"!=typeof e)return;return e=e[n[n.length-1]]}}e.exports={getConfiguration:r}},{}],3:[function(t,e,n){var r=!1;try{var i=Object.defineProperty({},"passive",{get:function(){r=!0}});window.addEventListener("testPassive",null,i),window.removeEventListener("testPassive",null,i)}catch(o){}e.exports=function(t){return r?{passive:!0,capture:!!t}:!!t}},{}],4:[function(t,e,n){function r(t,e){var n=[a,t,{name:t},e];return o("storeMetric",n,null,"api"),n}function i(t,e){var n=[c,t,{name:t},e];return o("storeEventMetrics",n,null,"api"),n}var o=t("handle"),a="sm",c="cm";e.exports={constants:{SUPPORTABILITY_METRIC:a,CUSTOM_METRIC:c},recordSupportability:r,recordCustom:i}},{}],5:[function(t,e,n){function r(){return c.exists&&performance.now?Math.round(performance.now()):(o=Math.max((new Date).getTime(),o))-a}function i(){return o}var o=(new Date).getTime(),a=o,c=t(12);e.exports=r,e.exports.offset=a,e.exports.getLastTimestamp=i},{}],6:[function(t,e,n){function r(t){return!(!t||!t.protocol||"file:"===t.protocol)}e.exports=r},{}],7:[function(t,e,n){function r(t,e){var n=t.getEntries();n.forEach(function(t){"first-paint"===t.name?l("timing",["fp",Math.floor(t.startTime)]):"first-contentful-paint"===t.name&&l("timing",["fcp",Math.floor(t.startTime)])})}function i(t,e){var n=t.getEntries();if(n.length>0){var r=n[n.length-1];if(u&&u<r.startTime)return;var i=[r],o=a({});o&&i.push(o),l("lcp",i)}}function o(t){t.getEntries().forEach(function(t){t.hadRecentInput||l("cls",[t])})}function a(t){var e=navigator.connection||navigator.mozConnection||navigator.webkitConnection;if(e)return e.type&&(t["net-type"]=e.type),e.effectiveType&&(t["net-etype"]=e.effectiveType),e.rtt&&(t["net-rtt"]=e.rtt),e.downlink&&(t["net-dlink"]=e.downlink),t}function c(t){if(t instanceof y&&!w){var e=Math.round(t.timeStamp),n={type:t.type};a(n),e<=v.now()?n.fid=v.now()-e:e>v.offset&&e<=Date.now()?(e-=v.offset,n.fid=v.now()-e):e=v.now(),w=!0,l("timing",["fi",e,n])}}function f(t){"hidden"===t&&(u=v.now(),l("pageHide",[u]))}if(!("init"in NREUM&&"page_view_timing"in NREUM.init&&"enabled"in NREUM.init.page_view_timing&&NREUM.init.page_view_timing.enabled===!1)){var u,s,d,p,l=t("handle"),v=t("loader"),m=t(9),g=t(3),y=NREUM.o.EV;if("PerformanceObserver"in window&&"function"==typeof window.PerformanceObserver){s=new PerformanceObserver(r);try{s.observe({entryTypes:["paint"]})}catch(h){}d=new PerformanceObserver(i);try{d.observe({entryTypes:["largest-contentful-paint"]})}catch(h){}p=new PerformanceObserver(o);try{p.observe({type:"layout-shift",buffered:!0})}catch(h){}}if("addEventListener"in document){var w=!1,b=["click","keydown","mousedown","pointerdown","touchstart"];b.forEach(function(t){document.addEventListener(t,c,g(!1))})}m(f)}},{}],8:[function(t,e,n){function r(t,e){if(!i)return!1;if(t!==i)return!1;if(!e)return!0;if(!o)return!1;for(var n=o.split("."),r=e.split("."),a=0;a<r.length;a++)if(r[a]!==n[a])return!1;return!0}var i=null,o=null,a=/Version\/(\S+)\s+Safari/;if(navigator.userAgent){var c=navigator.userAgent,f=c.match(a);f&&c.indexOf("Chrome")===-1&&c.indexOf("Chromium")===-1&&(i="Safari",o=f[1])}e.exports={agent:i,version:o,match:r}},{}],9:[function(t,e,n){function r(t){function e(){t(c&&document[c]?document[c]:document[o]?"hidden":"visible")}"addEventListener"in document&&a&&document.addEventListener(a,e,i(!1))}var i=t(3);e.exports=r;var o,a,c;"undefined"!=typeof document.hidden?(o="hidden",a="visibilitychange",c="visibilityState"):"undefined"!=typeof document.msHidden?(o="msHidden",a="msvisibilitychange"):"undefined"!=typeof document.webkitHidden&&(o="webkitHidden",a="webkitvisibilitychange",c="webkitVisibilityState")},{}],10:[function(t,e,n){function r(t,e){var n=[],r="",o=0;for(r in t)i.call(t,r)&&(n[o]=e(r,t[r]),o+=1);return n}var i=Object.prototype.hasOwnProperty;e.exports=r},{}],11:[function(t,e,n){function r(t,e,n){e||(e=0),"undefined"==typeof n&&(n=t?t.length:0);for(var r=-1,i=n-e||0,o=Array(i<0?0:i);++r<i;)o[r]=t[e+r];return o}e.exports=r},{}],12:[function(t,e,n){e.exports={exists:"undefined"!=typeof window.performance&&window.performance.timing&&"undefined"!=typeof window.performance.timing.navigationStart}},{}],ee:[function(t,e,n){function r(){}function i(t){function e(t){return t&&t instanceof r?t:t?u(t,f,a):a()}function n(n,r,i,o,a){if(a!==!1&&(a=!0),!l.aborted||o){t&&a&&t(n,r,i);for(var c=e(i),f=m(n),u=f.length,s=0;s<u;s++)f[s].apply(c,r);var p=d[w[n]];return p&&p.push([b,n,r,c]),c}}function o(t,e){h[t]=m(t).concat(e)}function v(t,e){var n=h[t];if(n)for(var r=0;r<n.length;r++)n[r]===e&&n.splice(r,1)}function m(t){return h[t]||[]}function g(t){return p[t]=p[t]||i(n)}function y(t,e){l.aborted||s(t,function(t,n){e=e||"feature",w[n]=e,e in d||(d[e]=[])})}var h={},w={},b={on:o,addEventListener:o,removeEventListener:v,emit:n,get:g,listeners:m,context:e,buffer:y,abort:c,aborted:!1};return b}function o(t){return u(t,f,a)}function a(){return new r}function c(){(d.api||d.feature)&&(l.aborted=!0,d=l.backlog={})}var f="nr@context",u=t("gos"),s=t(10),d={},p={},l=e.exports=i();e.exports.getOrSetContext=o,l.backlog=d},{}],gos:[function(t,e,n){function r(t,e,n){if(i.call(t,e))return t[e];var r=n();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(t,e,{value:r,writable:!0,enumerable:!1}),r}catch(o){}return t[e]=r,r}var i=Object.prototype.hasOwnProperty;e.exports=r},{}],handle:[function(t,e,n){function r(t,e,n,r){i.buffer([t],r),i.emit(t,e,n)}var i=t("ee").get("handle");e.exports=r,r.ee=i},{}],id:[function(t,e,n){function r(t){var e=typeof t;return!t||"object"!==e&&"function"!==e?-1:t===window?0:a(t,o,function(){return i++})}var i=1,o="nr@id",a=t("gos");e.exports=r},{}],loader:[function(t,e,n){function r(){if(!P++){var t=M.info=NREUM.info,e=g.getElementsByTagName("script")[0];if(setTimeout(u.abort,3e4),!(t&&t.licenseKey&&t.applicationID&&e))return u.abort();f(O,function(e,n){t[e]||(t[e]=n)});var n=a();c("mark",["onload",n+M.offset],null,"api"),c("timing",["load",n]);var r=g.createElement("script");0===t.agent.indexOf("http://")||0===t.agent.indexOf("https://")?r.src=t.agent:r.src=v+"://"+t.agent,e.parentNode.insertBefore(r,e)}}function i(){"complete"===g.readyState&&o()}function o(){c("mark",["domContent",a()+M.offset],null,"api")}var a=t(5),c=t("handle"),f=t(10),u=t("ee"),s=t(8),d=t(6),p=t(2),l=t(3),v=p.getConfiguration("ssl")===!1?"http":"https",m=window,g=m.document,y="addEventListener",h="attachEvent",w=m.XMLHttpRequest,b=w&&w.prototype,E=!d(m.location);NREUM.o={ST:setTimeout,SI:m.setImmediate,CT:clearTimeout,XHR:w,REQ:m.Request,EV:m.Event,PR:m.Promise,MO:m.MutationObserver};var x=""+location,O={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",agent:"js-agent.newrelic.com/nr-1215.min.js"},T=w&&b&&b[y]&&!/CriOS/.test(navigator.userAgent),M=e.exports={offset:a.getLastTimestamp(),now:a,origin:x,features:{},xhrWrappable:T,userAgent:s,disabled:E};if(!E){t(1),t(7),g[y]?(g[y]("DOMContentLoaded",o,l(!1)),m[y]("load",r,l(!1))):(g[h]("onreadystatechange",i),m[h]("onload",r)),c("mark",["firstbyte",a.getLastTimestamp()],null,"api");var P=0}},{}],"wrap-function":[function(t,e,n){function r(t,e){function n(e,n,r,f,u){function nrWrapper(){var o,a,s,p;try{a=this,o=d(arguments),s="function"==typeof r?r(o,a):r||{}}catch(l){i([l,"",[o,a,f],s],t)}c(n+"start",[o,a,f],s,u);try{return p=e.apply(a,o)}catch(v){throw c(n+"err",[o,a,v],s,u),v}finally{c(n+"end",[o,a,p],s,u)}}return a(e)?e:(n||(n=""),nrWrapper[p]=e,o(e,nrWrapper,t),nrWrapper)}function r(t,e,r,i,o){r||(r="");var c,f,u,s="-"===r.charAt(0);for(u=0;u<e.length;u++)f=e[u],c=t[f],a(c)||(t[f]=n(c,s?f+r:r,i,f,o))}function c(n,r,o,a){if(!v||e){var c=v;v=!0;try{t.emit(n,r,o,e,a)}catch(f){i([f,n,r,o],t)}v=c}}return t||(t=s),n.inPlace=r,n.flag=p,n}function i(t,e){e||(e=s);try{e.emit("internal-error",t)}catch(n){}}function o(t,e,n){if(Object.defineProperty&&Object.keys)try{var r=Object.keys(t);return r.forEach(function(n){Object.defineProperty(e,n,{get:function(){return t[n]},set:function(e){return t[n]=e,e}})}),e}catch(o){i([o],n)}for(var a in t)l.call(t,a)&&(e[a]=t[a]);return e}function a(t){return!(t&&t instanceof Function&&t.apply&&!t[p])}function c(t,e){var n=e(t);return n[p]=t,o(t,n,s),n}function f(t,e,n){var r=t[e];t[e]=c(r,n)}function u(){for(var t=arguments.length,e=new Array(t),n=0;n<t;++n)e[n]=arguments[n];return e}var s=t("ee"),d=t(11),p="nr@original",l=Object.prototype.hasOwnProperty,v=!1;e.exports=r,e.exports.wrapFunction=c,e.exports.wrapInPlace=f,e.exports.argsToArray=u},{}]},{},["loader"]);</script>
    <link href="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/styles/volkswagen_d6_vwoa-theme.css" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/favicons/volkswagen_d6_vwoa/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/favicons/volkswagen_d6_vwoa/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/favicons/volkswagen_d6_vwoa/favicon-16x16.png">
<script src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/javascripts/base/jquery-3.5.0.min.js"></script>
<script type="application/javascript" src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/javascripts/base/PasswordRevealer.js"></script>
<script type="application/javascript" src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/javascripts/base/InputFieldSessionPersistence.js"></script>
<script type="application/javascript" src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/javascripts/base/OnDocumentLoaded.js"></script>
<script type="application/javascript" src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/javascripts/base/TimeElapsedCounter.js"></script>
<script type="application/javascript" src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/javascripts/base/ErrorRemover.js"></script>
<script type="application/javascript" src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/javascripts/base/consent.js"></script>

<script type="application/javascript">
//<![CDATA[
    new OnDocumentLoaded(document, callback);

    function callback() {
        addHideMessageEventListener('[type="password"]');
        addHideMessageEventListener('[type="text"]');
        addHideMessageEventListener('[type="email"]');

        new PasswordRevealer(document, document.querySelector('[type="password"]'), '#input_password_revealer');
        new InputFieldSessionPersistence(document.getElementById("input_email"), window);
    }

    function addHideMessageEventListener(selector) {
        var element = document.querySelector(selector);
        if (element) {
            element.addEventListener("keydown", hideMessage);
        }
    }

    function hideMessage() {
        new ErrorRemover(document);
    }

    function isNotIE() {
        try {
            var ua = window.navigator.userAgent;
            var msie = ua.indexOf("MSIE ");
            var isIEUpToVersion11 = msie > 0;
            var isIEFromVersion11 = !!navigator.userAgent.match(/Trident.*rv\:11\./);
            var isIE = isIEUpToVersion11 || isIEFromVersion11;
            return !isIE;
        } catch (e) {
            return true;
        }
    }
//]]>
</script>
    <script>
      window._IDK = {
        templateModel: {"clientLegalEntityModel":{"clientId":"08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com","clientAppName":"VW Owner's Portal","clientAppDisplayName":"VW Owner's Portal","legalEntityInfo":{"name":"Volkswagen of America","shortName":"VWOA","productName":"Volkswagen ID","theme":"volkswagen_d6_vwoa","defaultLanguage":"en","termAndConditionsType":"DEFAULT","legalProperties":{"revokeDataContact":"https://vwoaid.na.vwgroup.io","imprintText":"IMPRINT","countryOfJurisdiction":"DE"}},"imprintTextKey":"imprint.link.text"},"template":"loginIdentifier","hmac":"6d9ddb67ee80951483c59960df55d6e4372485a1e3851a0c1d5b3c59d1db8c35","relayState":"232c509a165bb8bdebdaae07241bfa5ca2e7937d","emailPasswordForm":{"email":null,"password":null},"error":"validator.email.invalid"},
        currentLocale: 'en',
        csrf_parameterName: '_csrf',
        csrf_token: 'f984bb9e-65d2-419f-8cda-1a03873538e6'
      };
    </script>
</head>
<body>

<div id="page-container-background">
</div>

<div class="body-container">
        <div id="header">
            <div></div>
            <div></div>
            <div></div>
        </div>



    <div class="page-container">
        <div class="page-content">
            <div class="hide spacer-top"></div>


                <div id="legal-entity" class="legal-entity">
                    <div class="legal-entity-logo"></div>
                    <div id="legal-entity-name" class="legal-entity-name">Volkswagen ID</div>
                </div>


<form class="content" id="emailPasswordForm" name="emailPasswordForm" method="POST" novalidate="true" action="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/login/identifier">
    <div id="title" class="title">
        <div class="primary-title">Welcome</div>
        <div class="sub-title">to VW Owner's Portal.</div>
    </div>
    <input type="hidden" id="csrf" name="_csrf" value="f984bb9e-65d2-419f-8cda-1a03873538e6">
    <input type="hidden" id="input_relayState" name="relayState" value="232c509a165bb8bdebdaae07241bfa5ca2e7937d">
    <input type="hidden" id="hmac" name="hmac" value="6d9ddb67ee80951483c59960df55d6e4372485a1e3851a0c1d5b3c59d1db8c35">
    <div class="inputs">
<div class="group error">
    <input id="input_email" name="email" type="email" required="true" autofocus="true" onkeyup="this.setAttribute('input-value',this.value)" input-value="__USERNAME_REDACTED__">
    <span class="bar"></span>
    <label for="input_email">Email</label>
    <span class="message">Email must be a valid email address</span>


</div>
    </div>
    <div class="btn-group-single">
<button id="next-btn" class="btn zenith-button btn-active" type="submit">
    Next
</button>
    </div>
    <div class="link">
        <a id="signup-link" class="zenith-link" href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/register/identifier?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d">
        Create account
        </a>
    </div>

    <script type="application/javascript" src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/javascripts/base/InputFieldsButtonEnabler.js"></script>
    <script>
        new OnDocumentLoaded(document, callback);

        function callback() {
            new InputFieldsButtonEnabler(document.querySelector("#input_email"), document.querySelector("#next-btn"));
        }
    </script>
</form>


            <div class="hide spacer-bottom"></div>

            <footer>


    <ul>
        <li><a href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/imprint-page?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d" id="imprint">Imprint</a></li>
        <li><a href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/termsOfUse-page?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d" id="terms-of-use">Terms of Use</a></li>
        <li><a href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/dataPrivacy-page?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d" id="data-privacy">Data Privacy Policy</a></li>
        <li><a href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/cookiePolicy-page?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d" id="cookie-policy">Cookie Policy</a></li>
        <li><a href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/licenses-page?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d" id="licenses">3rdParty Licenses</a></li>
    </ul>
            </footer>
        </div>
    </div>
        <footer>


    <ul>
        <li><a href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/imprint-page?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d" id="imprint">Imprint</a></li>
        <li><a href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/termsOfUse-page?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d" id="terms-of-use">Terms of Use</a></li>
        <li><a href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/dataPrivacy-page?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d" id="data-privacy">Data Privacy Policy</a></li>
        <li><a href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/cookiePolicy-page?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d" id="cookie-policy">Cookie Policy</a></li>
        <li><a href="/signin-service/v1/08f58df9-f4f2-47a3-a37d-75f9bd58db0e@apps_vw-dilab_com/licenses-page?relayState=232c509a165bb8bdebdaae07241bfa5ca2e7937d" id="licenses">3rdParty Licenses</a></li>
    </ul>
        </footer>
</div>

<script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"errorBeacon":"bam.nr-data.net","licenseKey":"0452f39fd4","agent":"","beacon":"bam.nr-data.net","applicationTime":26,"applicationID":"70920201","transactionName":"NVVTZkpXXRcFURIKWgwfYkJKX10DJ10IF0cNXF1XShlIBwhbAw1BK1RMHVRZVA0KHQ8HUAxEWFRRU0FETHUjNxw=","queueTime":0}</script>
<script type="text/javascript" src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/na/a97001adc36590824fc915d24e08d26d32a8823c/signIn.bundle.js"></script>


</body></html>
Traceback (most recent call last):
  File "main.py", line 65, in main
    passwordInput = WebDriverWait(driver, pageLoadTimeout).until(
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x558529805a23 <unknown>
#1 0x5585292d0e18 <unknown>
#2 0x558529307151 <unknown>
#3 0x558529307311 <unknown>
#4 0x558529339ec4 <unknown>
#5 0x5585293249bd <unknown>
#6 0x558529337c5b <unknown>
#7 0x558529324883 <unknown>
#8 0x5585292fa3fa <unknown>
#9 0x5585292fb4c5 <unknown>
#10 0x55852983516d <unknown>
#11 0x55852984b5bb <unknown>
#12 0x558529836e75 <unknown>
#13 0x55852984be85 <unknown>
#14 0x55852982a86f <unknown>
#15 0x558529866ae8 <unknown>
#16 0x558529866c68 <unknown>
#17 0x558529881aad <unknown>
#18 0x7faca07a3ea7 <unknown>
```

**Comment by nmiodice** [comment]
It looks like there was an issue with the email you submitted:

```html
<span class="message">Email must be a valid email address</span>
```

Can you confirm that the `USERNAME` variable is a valid email? `echo $USERNAME`

**Comment by chandrasg** [comment]
That is it! echo $USERNAME shows the username of my Mac even when I export the email to it.

**Comment by nmiodice** [comment]
Interesting! Not sure why that would be - I am running from a Mac as well.

If you look in `run.sh` you should be able to modify the command.

I'm not at my computer, but it will be something like the following change:

`-e USERNAME=$USERNAME`

Becomes

`-e USERNAME=foo@gmail.com`

**Comment by nmiodice** [comment]
> That is it! echo $USERNAME shows the username of my Mac even when I export the email to it. 

Interesting! Not sure why that would be - I am running from a Mac as well.

If you look in `run.sh` you should be able to modify the command.

I'm not at my computer, but it will be something like the following change:

`-e USERNAME=$USERNAME`

Becomes

`-e USERNAME=foo@gmail.com`

**Comment by nmiodice** [comment]
> That is it! echo $USERNAME shows the username of my Mac even when I export the email to it. 

What command do you use to export and run the program?

**Comment by chandrasg** [comment]
adding the credentials to run.sh and running it directly worked! 

i was doing: 
export ***@***.*** ***@***.***> 
export PASSWORD= ***@***.***>pwd
./run.sh

**Comment by nmiodice** [comment]
> adding the credentials to run.sh and running it directly worked! i was doing: export ***@***.*** ***@***.***> export PASSWORD= ***@***.***>pwd ./run.sh

Ahh, I see. I think your syntax may be wrong. The correct incantation, assuming credentials `foo@gmail.com` with password `my-secret-password` should be:

```bash
export USERNAME="foo@gmail.com"
export PASSWORD="my-secret-password"

./run.sh
```

**Comment by chandrasg** [comment]
Tried with the double quotes too actually and had the same issue :D

**Comment by nmiodice** [comment]
Closing this, as the issue seems to be with your shell configuration and not the code
